import { COMMON_VALUES } from '@/localization/ui/common'

export const META_RESUME = {
  title: `Resume | ${COMMON_VALUES.nameDanielKrsiak} — ${COMMON_VALUES.reactDeveloper}`,
  description: `Experienced ${COMMON_VALUES.reactDeveloper} skilled in ${COMMON_VALUES.javaScriptShort}, ${COMMON_VALUES.typeScriptShort}, ${COMMON_VALUES.react}, ${COMMON_VALUES.next}, ${COMMON_VALUES.redux}, QA Automation, team leadership, and localization project management.`,
  keywords: {
    resume: 'Resume',
    nameDanielKrsiak: COMMON_VALUES.nameDanielKrsiak,
    reactDeveloper: COMMON_VALUES.reactDeveloper,
    qaAutomationSpecialist: 'QA Automation Specialist',
    teamLeader: 'Team Leader',
    localizationManager: 'Localization Manager',
    javaScript: COMMON_VALUES.javaScript,
    react: COMMON_VALUES.react,
    typeScript: COMMON_VALUES.typeScript,
    redux: COMMON_VALUES.redux,
    cypress: COMMON_VALUES.cypress,
    playwright: COMMON_VALUES.playwright,
    dashboardApplicationDevelopment: 'Dashboard Application Development',
    bankingWebsiteDevelopment: 'Banking Website Development',
    saasCompany: 'SaaS Company',
    microsoftWindows: 'Microsoft Windows',
    localizationExpert: 'Localization Expert',
    frontEndDevelopment: 'Front-End Development',
    softwareTestingAutomation: 'Software Testing & Automation',
    agileMethodologies: 'Agile Methodologies',
    uiUxDevelopment: 'UI/UX Development',
    crossFunctionalCollaboration: 'Cross-functional Collaboration',
    ciCd: 'Continuous Integration / Continuous Delivery (CI/CD)',
    versionControl: 'Version Control (Git)',
    tdd: 'Test-Driven Development (TDD)',
    unitIntegrationTesting: 'Unit & Integration Testing',
  },
}

export const RESUME = {
  resume: 'Resume',
  resumeTextOnly: 'Resume',
  downloadResume: 'Download Resume in\u00A0PDF',
  versionPDF: 'PDF',
  descriptionHighlightPDF: 'Visually designed',
  descriptionPDF: '— with colors, icons, and custom layout.',
  downloadResumeShortPDF: 'Download PDF',
  versionDOCX: 'DOCX',
  descriptionHighlightDOCX: 'ATS version',
  descriptionDOCX: '— no colors, no icons, just clean text.',
  downloadResumeShortDOCX: 'Download DOCX',
  openToWork: 'Open To\u00A0work',
  openToNetworking: 'Networking',
  scanQR: 'Scan My\u00A0Contact',
  feelFreeTo: 'Feel free to\u00A0scan my contact.',
  regardingJobOpportunities: 'to\u00A0hire\u00A0me.',
  forNetworkingOnLinkedIn: 'to\u00A0network.',
  callMe: 'Call\u00A0me',
  sendAnEmail: 'send\u00A0an\u00A0email',
  connectOnLinkedIn: 'connect on\u00A0LinkedIn',
}

export const CAREER_PATH = {
  heading: 'Career Path',
  text1: `My path over the\u00A0years to\u00A0become a\u00A0freelance`,
  text2: COMMON_VALUES.reactDeveloperNBSP,
}
