# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates
    schedule:
      interval: 'monthly'
    # Ignore updates for specified packages
    ignore:
      - dependency-name: 'flowbite'
      - dependency-name: 'flowbite-react'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: '@types/react'
      - dependency-name: '@types/react-dom'
      - dependency-name: 'tailwindcss'
