# Add PR labels based on branch names
ARIA:
  - head-branch: ['^aria', 'aria', '.*aria.*']

Build:
  - head-branch: ['^build', 'build', '.*build.*']

Chore:
  - head-branch: ['^chore', 'chore', '.*chore.*']

CICD:
  - head-branch: ['^cicd', 'cicd', '.*cicd.*']

Dependabot:
  - head-branch: ['^dependabot', 'dependabot', '.*dependabot.*']

Dependencies:
  - head-branch: ['^deps', 'deps', '.*deps.*']

Docs:
  - head-branch: ['^docs', 'docs', '.*docs.*']

Feature:
  - head-branch: ['^feat', 'feat', '.*feat.*', '^feature', 'feature', '.*feature.*']

Fix:
  - head-branch: ['^fix', 'fix', '.*fix.*']

Hotfix:
  - head-branch: ['^hotfix', 'hotfix', '.*hotfix.*']

ImgBot:
  - head-branch: ['^imgbot', 'imgbot', '.*imgbot.*']

Localization:
  - head-branch: ['^loc', 'loc', '.*loc.*', '^localization', 'localization', '.*localization.*']

Performance:
  - head-branch: ['^perf', 'perf', '.*perf.*', '^performance', 'performance', '.*performance.*']

Refactor:
  - head-branch: ['^ref', 'ref', '.*ref.*', '^refactor', 'refactor', '.*refactor.*']

Revert:
  - head-branch: ['^revert', 'revert', '.*revert.*']

Style:
  - head-branch: ['^style', 'style', '.*style.*']

Test - JEST:
  - head-branch: ['^jest', 'jest', '.*jest.*', '^unit', 'unit', '.*unit.*']

Test - Playwright:
  - head-branch: ['^playwright', 'playwright', '.*playwright.*', '^e2e', 'e2e', '.*e2e.*']
