import { COMMON_VALUES } from '../ui/common'

export const META_RESUME = {
  title: `Resume | ${COMMON_VALUES.nameDanielKrsiak} — ${COMMON_VALUES.reactDeveloper}`,
  description: `Experienced ${COMMON_VALUES.reactDeveloper} skilled in ${COMMON_VALUES.javaScriptShort}, ${COMMON_VALUES.typeScriptShort}, ${COMMON_VALUES.react}, ${COMMON_VALUES.next}, ${COMMON_VALUES.redux}, QA Automation, team leadership, and localization project management.`,
  keywords: {
    resume: 'Resume',
    nameDanielKrsiak: COMMON_VALUES.nameDanielKrsiak,
    reactDeveloper: COMMON_VALUES.reactDeveloper,
    qaAutomationSpecialist: 'QA Automation Specialist',
    teamLeader: 'Team Leader',
    localizationManager: 'Localization Manager',
    javaScript: COMMON_VALUES.javaScript,
    react: COMMON_VALUES.react,
    typeScript: COMMON_VALUES.typeScript,
    redux: COMMON_VALUES.redux,
    cypress: COMMON_VALUES.cypress,
    playwright: COMMON_VALUES.playwright,
    dashboardApplicationDevelopment: 'Dashboard Application Development',
    bankingWebsiteDevelopment: 'Banking Website Development',
    saasCompany: 'SaaS Company',
    microsoftWindows: 'Microsoft Windows',
    localizationExpert: 'Localization Expert',
    frontEndDevelopment: 'Front-End Development',
    softwareTestingAutomation: 'Software Testing & Automation',
    agileMethodologies: 'Agile Methodologies',
    uiUxDevelopment: 'UI/UX Development',
    crossFunctionalCollaboration: 'Cross-functional Collaboration',
    ciCd: 'Continuous Integration / Continuous Delivery (CI/CD)',
    versionControl: 'Version Control (Git)',
    tdd: 'Test-Driven Development (TDD)',
    unitIntegrationTesting: 'Unit & Integration Testing',
  },
}
