// Import ICON_EMOJI if needed for ARIA labels
// import { ICON_EMOJI } from '../constants/icons'

export const ARIA_LABELS = {
  quote: 'Quote',
  toggleMenu: 'Toggle Menu',
  menu: 'Menu',
  breadcrumbs: 'Breadcrumbs',
  galleryProjectShowcase: 'Gallery — Project showcase',
  galleryActiveImage: 'Active image',
  galleryThumbnails: 'Gallery thumbnails',
  galleryThumbnail: 'Thumbnail',
  skipToMainContent: 'Skip to main content',
  skipToNavigation: 'Skip to navigation',
  menuExpanded: 'Menu expanded',
  menuCollapsed: 'Menu collapsed',
  liveRegion: 'Live updates',
  statusUpdate: 'Status update',
  galleryImageSelected: 'Image selected',
  galleryImageNotSelected: 'Image not selected',
  galleryNavigation: 'Gallery navigation',
  mainContent: 'Main content',
  navigation: 'Navigation',
  complementary: 'Complementary content',
  siteHeader: 'Site header',
  siteFooter: 'Site footer',
  scrollToTopPage: 'Scroll to top of page',
  emoji: {
    icon: 'Emoji',
    starAndCrescent: 'Star and crescent',
    latinCross: 'Latin cross',
    house: 'House',
    moneyBag: 'Money bag',
    rocket: 'Rocket',
    speechBalloon: 'Speech balloon',
    bank: 'Bank',
    umbrellaWithRainDrops: 'Umbrella with rain drops',
    laptop: 'Laptop',
    books: 'Books',
    shoppingCart: 'Shopping cart',
    newspaper: 'Newspaper',
    memo: 'Memo',
    ghost: 'Ghost',
    verticalTrafficLight: 'Vertical traffic light',
    desktopComputer: 'Desktop computer',
    robot: 'Robot',
    star: 'Star',
    writingHand: 'Writing hand',
    foldedHands: 'Folded hands',
    church: 'Church',
    atomSymbol: 'Atom symbol',
    cog: 'Cog',
    artistPalette: 'Artist palette',
    officeBuilding: 'Office building',
    airplane: 'Airplane',
    poultryLeg: 'Poultry leg',
    link: 'Link',
    barChart: 'Bar chart',
    hammerAndWrench: 'Hammer and wrench',
    flag: {
      czechRepublic: 'Flag of Czech Republic',
      unitedKingdom: 'Flag of United Kingdom',
      spain: 'Flag of Spain',
      france: 'Flag of France',
      hungary: 'Flag of Hungary',
      germany: 'Flag of Germany',
      italy: 'Flag of Italy',
      netherlands: 'Flag of Netherlands',
      poland: 'Flag of Poland',
      slovakia: 'Flag of Slovakia',
      alandIslands: 'Flag of Åland Islands',
      southKorea: 'Flag of South Korea',
      japan: 'Flag of Japan',
      turkey: 'Flag of Turkey',
      tunisia: 'Flag of Tunisia',
      uae: 'Flag of United Arab Emirates',
      denmark: 'Flag of Denmark',
      sweden: 'Flag of Sweden',
      croatia: 'Flag of Croatia',
      greece: 'Flag of Greece',
      switzerland: 'Flag of Switzerland',
      austria: 'Flag of Austria',
    },
    globe: {
      showingAmericas: 'Globe showing Americas',
      showingEuropeAfrica: 'Globe showing Europe and Africa',
    },
    manLiftingWeights: 'Man lifting weights',
    personLiftingWeights: 'Person lifting weights',
    flexedBiceps: 'Flexed biceps',
    personFlexingBicepsLightSkinTone: 'Person flexing biceps with light skin tone',
    wavingHand: 'Waving hand',
    ninja: 'Ninja',
    manTechnologist: {
      lightSkinTone: 'Man technologist light skin tone',
    },
    man: {
      lightSkinTone: 'Man light skin tone',
      officeWorker: 'Man office worker',
    },
    woman: {
      officeWorker: 'Woman office worker',
    },
    cats: {
      ruzenka: 'Cat Růženka',
      nufka: 'Cat Ňufka',
    },
  },
}
