export const ICON_EMOJI = {
  latinCross: '✝️',
  starAndCrescent: '☪️',
  flagCzechRepublic: '🇨🇿',
  flagUnitedKingdom: '🇬🇧',
  flagSpain: '🇪🇸',
  flagFrance: '🇫🇷',
  flagHungary: '🇭🇺',
  flagGermany: '🇩🇪',
  flagItaly: '🇮🇹',
  flagNetherlands: '🇳🇱',
  flagPoland: '🇵🇱',
  flagSlovakia: '🇸🇰',
  flagAlandIslands: '🇦🇽',
  flagSouthKorea: '🇰🇷',
  flagJapan: '🇯🇵',
  flagTurkey: '🇹🇷',
  flagTunisia: '🇹🇳',
  flagUAE: '🇦🇪',
  flagDenmark: '🇩🇰',
  flagSweden: '🇸🇪',
  flagCroatia: '🇭🇷',
  flagGreece: '🇬🇷',
  flagSwitzerland: '🇨🇭',
  flagAustria: '🇦🇹',
  house: '🏠',
  moneyBag: '💰',
  rocket: '🚀',
  speechBalloon: '💬',
  bank: '🏦',
  umbrellaWithRainDrops: '☔',
  mobilePhone: '📱',
  laptop: '💻',
  books: '📚',
  shoppingCart: '🛒',
  globeShowingAmericas: '🌎',
  newspaper: '📰',
  globeShowingEuropeAfrica: '🌍',
  memo: '📝',
  ghost: '👻',
  verticalTrafficLight: '🚦',
  desktopComputer: '🖥️',
  robot: '🤖',
  star: '⭐',
  writingHand: '✍️',
  foldedHands: '🙏',
  church: '⛪',
  atomSymbol: '⚛️',
  cog: '⚙️',
  artistPalette: '🎨',
  officeBuilding: '🏢',
  airplane: '✈️',
  poultryLeg: '🍗',
  link: '🔗',
  barChart: '📊',
  hammerAndWrench: '🛠️',
  manLiftingWeights: '🏋️‍♂️',
  personLiftingWeights: '🏋️',
  flexedBiceps: '💪',
  personFlexingBicepsLightSkinTone: '💪🏻',
  wavingHand: '👋',
  ninja: '🥷',
  manTechnologist: {
    lightSkinTone: '👨🏻‍💻',
  },
  man: {
    lightSkinTone: '👨🏻',
    officeWorker: '👨‍💼',
  },
  woman: {
    officeWorker: '👩‍💼',
  },
  cat: {
    ruzenka: '😺',
    nufka: '😼',
  },
}

export const FLAGS_LOCALIZATION = {
  emojis: `${ICON_EMOJI.flagUnitedKingdom}\u00A0${ICON_EMOJI.flagCzechRepublic}\u00A0${ICON_EMOJI.flagSpain}\u00A0${ICON_EMOJI.flagFrance}\u00A0${ICON_EMOJI.flagHungary}\u00A0${ICON_EMOJI.flagGermany}\u00A0${ICON_EMOJI.flagItaly}\u00A0${ICON_EMOJI.flagNetherlands}\u00A0${ICON_EMOJI.flagPoland}`,
}
