name: Jest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run JEST tests
        run: npm test

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jest-report
          path: jest-report/
          retention-days: 7
