name: Jest Tests

on:
  pull_request:
    branches:
      - master

jobs:
  run-tests-jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm ci

      - name: Run JEST tests
        run: pnpm test

      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: jest-report
          path: jest-report/
          retention-days: 7
