name: Playwright Tests

on:
  # Temporarily disabled - will re-enable after fixing
  # pull_request:
  #   branches:
  #     - master

permissions:
  contents: read

jobs:
  run-tests-playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build the project
        run: bun run build

      - name: Install Playwright Browsers
        run: bunx playwright install --with-deps

      # Run local server
      # playwright.config.ts = should run the webServer:{}

      - name: Run Playwright tests
        run: bun run test:e2e

      - name: Archive test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
