name: Prettier Check Formatting

on:
  pull_request:
    branches:
      - master

jobs:
  run-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier 'check' to check the formatting
        run: npm run prettier:check
